version: "3.4"

services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - proxy_cert
      - proxy_dhparam
      - proxy_key
    environment:
      PROXY_HOST: "${HOST_IP}"
      PROXY_PORT: 5000

secrets:
  proxy_cert:
    file: ./nginx/secrets/cert.crt
  proxy_dhparam:
    file: ./nginx/secrets/dhparam.pem
  proxy_key:
    file: ./nginx/secrets/key.pem